API_URL="http://18.234.166.191:4000/"
LOCAL_API_URL="http://localhost:4000/"
ELECTIVO_1=["Área A: Participación y Argumentación", "Área B: Biología celular y molecular", "Área C: Ciencias del ejercicio físico y deportivo"]
ELECTIVO_2=["Área A: Economía y Sociedad", "Área B: Ciencias de la salud", "Área C: Diseño y arquitectura"]
ELECTIVO_3=["Área A: Comprensión Histórica del Presente", "Área B: Probabilidades y estadística descriptiva e inferencial", "Área B: Pensamiento computacional y programación"]
ELECTIVOS_FG=["Historia, Geografía y Cs. Sociales", "Artes Visuales"]
CUPOS="25"
CURSOS=["2º medio G", "2º medio B"]